inherit_from: .rubocop_todo.yml

## rubocop 関連の gem を require する
# require:
#   - rubocop-rails
#   - rubocop-rspec
#   - rubocop-performance

## 全体に適応する項目を定義。
AllCops:
  TargetRubyVersion: 2.6
  # TargetRailsVersion: 5.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/***/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'test/***/**/*'
    - 'config/***/**/*'
    - 'node_modules/**/*'

  NewCops: enable

# 括弧の前にスペースはないか
Layout/SpaceBeforeBrackets:
  Enabled: true
# タイプミス
Lint/AmbiguousAssignment:
  Enabled: true
# 非推奨の定数
Lint/DeprecatedConstants:
  Enabled: true
# 条件分岐の中に重複がないか
Lint/DuplicateBranch:
  Enabled: true
# 正規表現クラスの中に重複の有無
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
# 空のブロックの有無
Lint/EmptyBlock:
  Enabled: true
# 空の補間（代入？）の有無
Lint/EmptyClass:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
# Begin-endブロック内にreturnが存在するか
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
# 番号付きパラメータの有無
Lint/NumberedParameterAssignment:
  Enabled: true
# orの誤用により、定数に意図しない割当がないか
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
# シンボルに変換できないか
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
# エンドレスメソッドのチェック
Style/EndlessMethod:
  Enabled: true
Style/HashExcept:
  Enabled: true
# 冗長なBooleanの条件分岐があるか
Style/IfWithBooleanLiteralBranches:
  Enabled: true
# ifの条件分岐にて、条件を反転させてコードを簡略化できないか
Style/NegatedIfElseCondition:
  Enabled: true
# 常にnilを返すラムダはないか
Style/NilLambda:
  Enabled: true
# 冗長な引数はないか
Style/RedundantArgument:
  Enabled: true
Style/SwapValues:
  Enabled: true
# ハッシュの記法を指定する。
Style/HashSyntax:
  EnforcedStyle: ruby19
# メソッドの長さが最大値を超えていないか
Metrics/MethodLength:
  CountComments: false
  Max: 30
# クラスやモジュールを定期する際の記法を指定
Style/ClassAndModuleChildren:
  Enabled: false
# %i()を記述する際に配列にシンボルを用いていないか
Style/SymbolArray:
  Enabled: false
# 日本語のコメントを許可する。
Style/AsciiComments:
  Enabled: false
# 意味なく"(ダブルクォート)を使用していないか
Style/StringLiterals:
  Exclude:
    - 'Guardfile'
Style/FrozenStringLiteralComment:
  Enabled: false
# 複雑度の測定
Metrics/CyclomaticComplexity:
  Max: 10
# 最終行の空行はないか
Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

# todoリストの除外一覧
# gemの整列について
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'


Layout/ArgumentAlignment:
  Exclude:
    - 'app/models/role.rb'

Layout/MultilineOperationIndentation:
  Exclude:
    - 'Guardfile'

